version: "3.9"

services:
  web:
    build: .
    container_name: waapp-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Монтируем только нужные директории, избегаем полного монтирования кода
      - staticfiles:/app/staticfiles
      - media:/app/media
      # Если нужно отладить - раскомментируйте следующую строку
      # - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=apicore.settings
    # Добавляем healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/login/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  staticfiles:
  media: