version: "3.9"

services:
  web:
    build: .
    container_name: waapp-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app/apicore
